INCLUDES = -I../UsageEnvironment/include -I../groupsock/include -I../liveMedia/include -I../BasicUsageEnvironment/include -I../BackChannel/include
# Default library filename suffixes for each library that we link with.  The "config.*" file might redefine these later.

##### Change the following for your environment:
